# Generated by Django 5.2.4 on 2025-08-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_doctor_password_doctor_available_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
